[package]
name = "vpnyellod"
version = "0.1.1"
edition = "2021"
description = "YellowD VPN server agent: auto-setup WireGuard, register on vpn.yellod.dpdns.org, apply client peers. One codebase, x86_64 + aarch64."
license = "MIT"

[[bin]]
name = "vpnyellod"
path = "src/main.rs"

[profile.release]
opt-level = 2
